"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""
import sys
import itertools

def fib(n):
    if n == 0:
        return 0
    if n == 1:
        return 1
    return fib(n-1) + fib(n-2)

def even_fibs():
    n = 0
    while True:
        f = fib(n)
        if f % 2 == 0:
            yield f
        n = n+1

#print sum(i for i in even_fibs())
print sum(itertools.takewhile(lambda x: x < 4000000, even_fibs()))